### ISSUE TITLE
wget throws a "SSL error: SSL - Bad input parameters to function"

### ISSUE THREAD

**Issue by McGiverGim** [openwrt/uclient#4]
More info here: https://github.com/openwrt/openwrt/issues/15427

It worked until some weeks ago, where it started to fail with latest snapshot of OpenWrt.

The issue occurs when uclient-fetch tries to redirect over SSL from one host to another. So a redirect that works like this: `https://rany.eu.org/hi -> https://rany.eu.org/hi2` will work fine but `https://rany.eu.org/subdomain to https://subdomain.rany.eu.org` does not.

```
root@crappypi:~# wget -O/dev/null https://rany.eu.org/hi
Downloading 'https://rany.eu.org/hi'
Connecting to x:443
Redirected to /hi2 on rany.eu.org
HTTP error 404
root@crappypi:~# wget -O/dev/null https://rany.eu.org/subdomain
Downloading 'https://rany.eu.org/subdomain'
Connecting to x:443
Redirected to / on subdomain.rany.eu.org
SSL error: SSL - Bad input parameters to function
Connection error: Connection failed
```

**Comment by Neustradamus** [comment]
There is a change for this bug?

**Comment by McGiverGim** [comment]
Tested on latest snapshot version and it seems to be fixed. I close this, thanks!!!
